"""Email sender — delivers the daily report via SMTP."""

from __future__ import annotations

import os
import smtplib
from datetime import date
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import pandas as pd
from jinja2 import DictLoader, Environment

_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; color: #333; }
  h1   { color: #1F4E79; }
  table { border-collapse: collapse; width: 100%; }
  th   { background: #1F4E79; color: #fff; padding: 8px 12px; }
  td   { padding: 6px 12px; border-bottom: 1px solid #ddd; }
  .strong  { background: #e2efda; }
  .moderate{ background: #fff2cc; }
  .weak    { background: #fce4d6; }
</style>
</head>
<body>
  <h1>📊 Signal Scanner — {{ scan_date }}</h1>
  <p>Top {{ rows|length }} tickers by composite score.</p>
  <table>
    <tr>
      {% for col in columns %}<th>{{ col }}</th>{% endfor %}
    </tr>
    {% for row in rows %}
    <tr class="{{ row.tier }}">
      {% for col in columns %}<td>{{ row[col] }}</td>{% endfor %}
    </tr>
    {% endfor %}
  </table>
  <p style="color:#888;font-size:11px;">Generated by signal-scanner. Not financial advice.</p>
</body>
</html>
"""


def send_report(
    results: pd.DataFrame,
    scan_date: date,
    attachment: Path | None = None,
) -> None:
    """Send the daily report email.

    Reads SMTP credentials and recipient list from environment variables.
    """
    host = os.environ["SMTP_HOST"]
    port = int(os.environ.get("SMTP_PORT", 587))
    user = os.environ["SMTP_USER"]
    password = os.environ["SMTP_PASS"]
    recipients = [r.strip() for r in os.environ["REPORT_RECIPIENTS"].split(",")]

    # ── Build HTML body ───────────────────────────────────────────────────────
    display_cols = ["ticker", "exchange", "combo_score", "tier",
                    "rsi_value", "stoch_k", "vol_ann", "volume_ratio"]
    available = [c for c in display_cols if c in results.columns]
    top20 = results.head(20)[available].copy()
    top20["combo_score"] = top20["combo_score"].round(4) if "combo_score" in top20 else top20
    rows = top20.to_dict("records")

    env = Environment(loader=DictLoader({"report.html": _HTML_TEMPLATE}))
    html_body = env.get_template("report.html").render(
        scan_date=scan_date.isoformat(),
        columns=available,
        rows=rows,
    )

    # ── Assemble email ────────────────────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["Subject"] = f"Signal Scanner Report — {scan_date.isoformat()}"
    msg["From"] = user
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(html_body, "html"))

    if attachment and attachment.exists():
        with attachment.open("rb") as fh:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(fh.read())
        encoders.encode_base64(part)
        part.add_header("Content-Disposition", f'attachment; filename="{attachment.name}"')
        msg.attach(part)

    # ── Send ──────────────────────────────────────────────────────────────────
    use_tls = os.environ.get("SMTP_USE_TLS", "true").lower() == "true"
    with smtplib.SMTP(host, port) as server:
        if use_tls:
            server.starttls()
        server.login(user, password)
        server.sendmail(user, recipients, msg.as_string())
